#!/usr/bin/perl

#Coded By N0TZ3R0 a.k.a YSpoof

$HOME=$ENV{"HOME"};
$YTDL="$HOME/.local/bin/youtube-dlp";


if($ARGV[0] eq '-h' | $ARGV[0] eq '--help'| $ARGV[0] eq ''){
print("Youtube-DLP Helper\n\n");
print("Warning: youtube-dlp tool must be INSTALLED\n");
print("If it isn't, use ytdl -u to update/install\n");
print("FFMPEG is also needed, please install it manually !\n\n");
print("Usage:\n\n");
print("To download a video as mp3 use: ytdl <YTBlink>\n\n");
print("To keep the video file+mp3, use: ytdl -k <YTBlink>\n\n");
print("To download a video use: ytdl -v <YTBlink>\n\n");
print("To download an entire mp3 playlist use: ytdl -pm <YTBlink>\n\n");
print("To download an entire video playlist use: ytdl -pv <YTBlink>\n");

exit;}

if($ARGV[0] eq '-u'){
system("mkdir -p $HOME/.local/bin/");
system("wget https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp  -O $YTDL");
system("chmod a+x $YTDL");
exit;}

if($ARGV[0] eq '-v'){
$link=$ARGV[1];
system("$YTDL --no-playlist -f mp4 '$link'");
exit; }

if($ARGV[0] eq '-pm'){
$link=$ARGV[1];
system("$YTDL --yes-playlist -i -f mp4 -x --audio-format mp3 --audio-quality 320K '$link'");
exit;}

if($ARGV[0] eq '-pv'){
$link=$ARGV[1];
system("$YTDL --yes-playlist -i -f mp4 '$link'");
exit;}

if($ARGV[0] eq '-k'){
$link=$ARGV[1];
system("$YTDL --no-playlist -f mp4  -x -k --audio-format mp3 --audio-quality 320K '$link'");
exit;}

$link=$ARGV[0];
system("$YTDL --no-playlist -f mp4 -x --audio-format mp3 --audio-quality 320K '$link'");
exit;
