#!/usr/bin/perl

#Coded By N0tZ3r0 a.k.a YSpoof

$HOME=$ENV{"HOME"};
$YTDL="$HOME/.local/bin/youtube-dl";


if($ARGV[0] eq '-h' | $ARGV[0] eq '--help'| $ARGV[0] eq ''){
print("Youtube-DL Helper\n");
print("Warning: youtube-dl tool must be INSTALLED\n");
print("If it isn't, use ytdl -u to update/install\n");
print("Warning: You also need ffmpeg !\n\n");
print("Usage: ytdl <YTBlink>\n\n");
print("To download a video use: ytdl -v <YTBlink>\n\n");
print("To download an entire mp3 playlist use: ytdl -pm <YTBlink>\n\n");
print("To download an entire video playlist use: ytdl -pv <YTBlink>\n\n");
print("To keep the video file+mp3, use: ytdl -k <YTBlink>\n\n");
exit;}

if($ARGV[0] eq '-u'){
system("mkdir -p $HOME/.local/bin/");
system("wget https://yt-dl.org/downloads/latest/youtube-dl -O $YTDL");
system("chmod a+x $YTDL");
exit;}

if($ARGV[0] eq '-v'){
$link=$ARGV[1];
system("$YTDL -f mp4 --no-playlist '$link'");
exit; }

if($ARGV[0] eq '-pm'){
$link=$ARGV[1];
system("$YTDL -i -f mp4 -x --audio-format mp3 --audio-quality 320K '$link'");
exit;}

if($ARGV[0] eq '-pv'){
$link=$ARGV[1];
system("$YTDL -i -f mp4 '$link'");
exit;}

if($ARGV[0] eq '-k'){
$link=$ARGV[1];
system("$YTDL -f mp4 --no-playlist -x -k --audio-format mp3 --audio-quality 320K '$link'");
exit;}

$link=$ARGV[0];
system("$YTDL -f mp4 --no-playlist -x --audio-format mp3 --audio-quality 320K '$link'");
exit;
